[package]

name    = "sdl2"
description = "SDL2 bindings for Rust"
repository = "https://github.com/AngryLawyer/rust-sdl2"
documentation = "http://angrylawyer.github.io/rust-sdl2/sdl2/"
version = "0.27.3"
license = "MIT"
authors = [ "Tony Aldridge <tony@angry-lawyer.com>" ]
keywords = ["SDL", "windowing", "graphics"]

[lib]

name       = "sdl2"
path       = "src/sdl2/lib.rs"


[[test]]
name="events"
harness=false

[dependencies]
bitflags = "0.7"
libc = "0.2"
rand = "0.3"
lazy_static="0.2"

[dependencies.num]
version = "0.1.25"
default-features = false

[dependencies.sdl2-sys]
path = "sdl2-sys"
version = "0.27.0"

[dependencies.c_vec]
version = "1.0.*"
optional = true

[features]

default = []
ttf = []
image = []
gfx = ["c_vec"]
mixer = []

use-pkgconfig = [ "sdl2-sys/use-pkgconfig" ]
use_mac_framework = ["sdl2-sys/use_mac_framework"]
